app_identifier(ENV['APP_IDENTIFIER']) if ENV['APP_IDENTIFIER']
platform('ios')
app_version('1.0.5')

metadata_path('fastlane/metadata')
screenshots_path('fastlane/screenshots')
skip_binary_upload(true)
skip_metadata(false)
skip_screenshots(false)
overwrite_screenshots(false)
submit_for_review(false)
run_precheck_before_submit(false)
precheck_include_in_app_purchases(false)
force(true)
